_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 13
                - 55
                - 61
            "4": 3.10.18
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-arm64
